version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "23:15"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 3.2.2
